### ISSUE TITLE
`@typescript-eslint/typescript-estree` warning with newer Typescript versions

### ISSUE THREAD

**Issue by toomuchdesign** [musement/eslint-plugin#9]
**Describe the bug**

`typescript-eslint` released a new major [version (v5)](https://github.com/typescript-eslint/typescript-eslint/blob/main/CHANGELOG.md#500-2021-10-11) which is not reachable by `@musement/eslint-plugin` users since `typescript-eslint` dependencies are [locked to v4.17.x](https://github.com/musement/eslint-plugin/blob/v1.0.1/package.json#L27).

This will cause `@typescript-eslint/typescript-estree` raising the following warning when linting a project using a recent Typescript version:

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.3.0

YOUR TYPESCRIPT VERSION: 4.5.4

Please only submit bug reports when using the officially supported version.

=============
```

**To Reproduce**
Update any project using  `@musement/eslint-plugin` and Typescript to use last available Typescript version and run `eslint`.

**Expected behavior**
eslint should run without any error/warining.

I guess we might consider releasing a new major version with new `typescript-eslint` deps set to `5.x.x`.

Also shouldn't we consider switching current dependencies to use `^` instead of `~`?

**Device info:**
 - OS: MacOs

**Additional context**

**Comment by przemkow** [comment]
Hi, @toomuchdesign thanks for opening an issue! I controlled briefly other repositories and I think we can safely update all dependencies to the newest version. A few months ago some packages were lacking support for Eslint 8 however as far as I see now everything is updated. 

About using `^` instead of `~` i think it's also a good idea so every project can use a minor version aligned to its requirements.

**Comment by aurelienlair** [comment]
Guys I opened a MR for this https://github.com/musement/eslint-plugin/pull/16

**Comment by davidcsmtui** [comment]
As far as I can see, this bug is already closed. I think should be moved to Done column in the [Project board](https://github.com/musement/eslint-plugin/projects/1)
